### ISSUE TITLE
Basic Example results in Assertion Error

### ISSUE THREAD

**Issue by zahidirfan** [cavalab/fomo#4]
After work around of Issue #3 (added NoneType = type(None) ).

I get the following error when executing the basic code. 

```
from fomo import FomoClassifier
from pmlb import pmlb
X,y = pmlb.fetch_data('adult', return_X_y=True)
groups = ['race','sex']
est = FomoClassifier()
est.fit(X,y, protected_features=groups)

```

AssertionError: X should be a dataframe
"""

The above exception was the direct cause of the following exception:

AssertionError                            Traceback (most recent call last)
Cell In[2], line 6
      4 groups = ['race','sex']
...
    769     return self._value
    770 else:
--> 771     raise self._value

AssertionError: X should be a dataframe

**Comment by lacava** [comment]
X does need to be a dataframe. Try this instead: 

```
dataset = pmlb.fetch_data('adult')
dataset = dataset.sample(n=2000)
X = dataset.drop('target',axis=1)
y = dataset['target']
```
